export const images = {
    chaletVuDuPont: require('./chalet-vu-du-pont.jpg'),
    chaletVuDeFace: require('./chalet-vu-de-face.jpg'),
    autourDuChalet12: require('./autour-du-chalet-12.jpg'),
    chiensDeTraineaux: require('./chiens-de-traineaux.jpg'),
    skiAlpin: require('./ski-alpin.jpeg'),
    skiDeFond: require('./ski-de-fond.jpg'),
    raquettes: require('./raquettes.jpg'),
    luge: require('./luge.jpg'),
    snowboard: require('./snowboard.jpg'),
    fatbike: require('./fatbike.jpg'),
    randonneeGlacier: require('./randonnee-glacier.jpg'),
    patinage: require('./patinage.jpg'),
    randonnee: require('./randonnee.jpeg'),
    vtt: require('./vtt.jpeg'),
    parapente: require('./parapente.jpg'),
    aquatique: require('./baignade.jpeg'),
    viaFerrata: require('./via-ferrata.jpeg'),
    voile: require('./voile.jpeg'),
    montgolfiere: require('./montgolfiere.webp'),
    rafting: require('./rafting.jpeg'),
    equitation: require('./equitation.jpg'),
  };
  